version: "3.8"

#volumes:
#  caddy-config:
#  caddy-data:

services:
  iscc-app:
    image: ghcr.io/iscc/iscc-web:main
    init: true
    env_file: .env

#  caddy:
#    image: caddy:2.6.1-alpine
#    restart: unless-stopped
#    env_file: .env
#    environment:
#      - ISCC_SDK_GRANULAR=${ISCC_SDK_GRANULAR}
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile
#      - caddy-config:/config
#      - caddy-data:/data
#    ports:
#      - target: "$ISCC_WEB_SITE_PORT"
#        published: $ISCC_WEB_SITE_PORT # issuer-api
#        protocol: tcp
#        mode: host
#      - target: "$ISSUER_API_PORT"
#        published: $ISSUER_API_PORT # issuer-api
#        protocol: tcp
#        mode: host
#      - target: "$VERIFIER_API_PORT"
#        published: $VERIFIER_API_PORT # verifier-api
#        protocol: tcp
#        mode: host
#    depends_on:
#      - iscc-app

  issuer-api:
    platform: linux/x86_64
    image: docker.io/waltid/issuer-api:${VERSION_TAG:-latest}
    pull_policy: always
#    depends_on:
#      - caddy
    env_file:
      - .env
    volumes:
      - ./issuer-api/config:/waltid-issuer-api/config

  verifier-api:
    platform: linux/x86_64
    image: docker.io/waltid/verifier-api:${VERSION_TAG:-latest}
    pull_policy: always
#    depends_on:
#      - caddy
    env_file:
      - .env
    volumes:
      - ./verifier-api/config:/waltid-verifier-api/config
