services:

  issuer-api:
    platform: linux/x86_64
    image: docker.io/waltid/issuer-api:${VERSION_TAG:-latest}
    pull_policy: always
    depends_on:
      - caddy
    env_file:
      - .env
    volumes:
      - ./issuer-api/config:/waltid-issuer-api/config

  verifier-api:
    platform: linux/x86_64
    image: docker.io/waltid/verifier-api:${VERSION_TAG:-latest}
    pull_policy: always
    depends_on:
      - caddy
    env_file:
      - .env
    volumes:
      - ./verifier-api/config:/waltid-verifier-api/config


  caddy:
    image: docker.io/caddy:2
    restart: unless-stopped
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    ports:

      - target: "$ISSUER_API_PORT"
        published: $ISSUER_API_PORT # issuer-api
        protocol: tcp
        mode: host

      - target: "$VERIFIER_API_PORT"
        published: $VERIFIER_API_PORT # verifier-api
        protocol: tcp
        mode: host

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile


