
server:
  port: 8082
  servlet:
    context-path: /proven-ai/api/v1
logging:
  level:
    dev.ctrlspace: DEBUG
    org.springframework: INFO

spring:
  mvc:
    format:
      date-time: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DATABASE_URL:no-env-variable}
    username: ${DATABASE_USERNAME:no-env-variable}
    password: ${DATABASE_PASSWORD:no-env-variable}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
    name: proven-ai-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev.gendox.ctrlspace.dev/idp/realms/gendox-idp-dev
          jwk-set-uri: https://dev.gendox.ctrlspace.dev/idp/realms/gendox-idp-dev/protocol/openid-connect/certs

keycloak:
  base-url: https://dev.gendox.ctrlspace.dev/idp
  token-uri: https://dev.gendox.ctrlspace.dev/idp/realms/gendox-idp-dev/protocol/openid-connect/token
  realm: gendox-idp-dev
  client-id: ${KEYCLOAK_CLIENT_ID:no-env-variable}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:no-env-variable}

management:
  tracing:
    sampling:
      probability: 1.0

  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  observations:
    key-values:
      application: proven-ai-api

springdoc:
  swagger-ui:
    path: /api-documentation

proven-ai:
  ssi:
    issuer-private-jwk: ${ISSUER_PRIVATE_JWK:no-env-variable}
    issuer-did: ${ISSUER_DID:no-env-variable}
    verifier:
      url: https://proven-ai-verifier.ctrlspace.dev/ssi/verifier
    issuer:
      url: https://proven-ai-issuer.ctrlspace.dev/ssi/issuer
  openapi:
    servers:
#      concat hard coded url string with the context path from params
      local-url: http://localhost:8082${server.servlet.context-path}
      dev-url: https://dev.proven-ai.ctrlspace.dev${server.servlet.context-path}
      prod-url: https://app.proven-ai.ctrlspace.dev${server.servlet.context-path}
  domains:
    gendox:
      base-url: https://gendox-api.ctrlspace.dev
      context-path: /gendox/api/v1
      apis:
        user-profile: /profile
        semantic-search: /messages/semantic-search
        completion: /messages/semantic-completion
        web-hook: /proven-ai/web-hook
    proven-ai-frontend:
      base-url: https://proven-ai.ctrlspace.dev
      context-path: ${server.servlet.context-path}
  blockchain:
    rpc-url: ${BLOCKCHAIN_RPC_URL:no-env-variable}
    contract-address: ${BLOCKCHAIN_CONTRACT_ADDRESS:no-env-variable}
    private-key: ${BLOCKCHAIN_PRIVATE_KEY:no-env-variable}
    chain-id: ${BLOCKCHAIN_CHAIN_ID:0}


