
spring:
  datasource:
    url: ${DEV_DATABASE_URL}
    username: ${DEV_DATABASE_USERNAME}
    password: ${DEV_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10

proven-ai:
  ssi:
    verifier:
      url: https://dev-proven-ai-verifier.ctrlspace.dev/ssi/verifier
    issuer:
      url: https://dev-proven-ai-issuer.ctrlspace.dev/ssi/issuer

