
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${DATABASE_USERNAME:gendox_user}
    password: ${DATABASE_PASSWORD:root}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8880/idp/realms/gendox-idp-dev
          jwk-set-uri: http://host.docker.internal:8880/idp/realms/gendox-idp-dev/protocol/openid-connect/certs


keycloak:
  base-url: http://host.docker.internal:8880/idp
  token-uri: http://host.docker.internal:8880/idp/realms/gendox-idp-dev/protocol/openid-connect/token
  realm: gendox-idp-dev
  client-id: ${KEYCLOAK_CLIENT_ID:no-env-variable}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:no-env-variable}

proven-ai:
  ssi:
    verifier:
      url: http://host.docker.internal:7003/verifier/openid4vc/verify
    issuer:
      url: http://host.docker.internal:7002/issuer/openid4vc/jwt/issue


  domains:
    gendox:
      base-url: http://host.docker.internal:8080
    proven-ai-frontend:
      base-url: http://localhost:3001
  blockchain:
    rpc-url: HTTP://127.0.0.1:7545  # Local Ganache env
    contract-address: '0xdA7B2e713d7b3674f2f90Ed14C1100188C91a6cd'
#    Dont try to hack it, this is the default ganache private key
    private-key: '0x99c026d99302999c57c4de1646e1ead4da58e0b753b7f8a3392269e71c2ddd0d'
    chain-id: 1337


