
spring:
  datasource:
#    url: ${DEV_DATABASE_URL}
#    username: ${DEV_DATABASE_USERNAME}
#    password: ${DEV_DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1

proven-ai:
  ssi:
    verifier:
      url: https://dev-proven-ai-verifier.ctrlspace.dev/ssi/verifier
    issuer:
      url: https://dev-proven-ai-issuer.ctrlspace.dev/ssi/issuer
  domains:
    gendox:
      base-url: http://localhost:5002
    proven-ai-frontend:
      base-url: http://localhost:3000

