
proven-ai:
  ssi:
    verifier:
      url: https://dev-proven-ai-verifier.ctrlspace.dev/ssi/verifier
    issuer:
      url: https://dev-proven-ai-issuer.ctrlspace.dev/ssi/issuer
  domains:
    gendox:
      base-url: https://dev.gendox.ctrlspace.dev
    proven-ai-frontend:
      base-url: https://dev.proven-ai.ctrlspace.dev

