
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10

proven-ai:
  ssi:
    verifier:
      url: https://dev-proven-ai-verifier.ctrlspace.dev/ssi/verifier
    issuer:
      url: https://dev-proven-ai-issuer.ctrlspace.dev/ssi/issuer
  domains:
    gendox:
      base-url: http://localhost:8080
    proven-ai-frontend:
      base-url: http://localhost:3001

